# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Union' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Union
  pod 'Parse'
  pod 'AlamofireImage'
  target 'UnionTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UnionUITests' do
    # Pods for testing
  end

end
